name: snow
favicon: null
layout_spectrum: 0.8128197793848813
typography_spectrum: 0.5172721662092954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07640784094110131
  lightness: 0.21526959026232362
  saturation: 0.389392287703231
  rhythmicContrast: 0.3659162316471338
purpose: []
