color:
  brandStrength: 0.07640784094110131
  saturation: 0.389392287703231
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.2152695902623236
  rhythmicContrast: 0.3659162316471338
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.8128197793848813
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: snow
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5172721662092954
